---
- name: 创建临时目录存放镜像
  file:
    path: "/tmp/images"
    state: directory
    mode: '0755'


- name: 复制 volcano 镜像文件到临时目录
  copy:
    src: "{{ playbook_dir }}/images/{{ ansible_architecture }}/{{ item }}"
    dest: "/tmp/{{ item }}"
    mode: 0644
    directory_mode: 0755           # 为目录设置单独的权限（可选）
    remote_src: no         # 表示src是本地路径，不是远程路径
    force: yes             # 如果目标存在则覆盖
  with_items:
    - "volcano-metrics.tar"
    - "volcano-images.tar"


- name: 加载 volcano 镜像到 Docker
  shell: "docker load -i /tmp/{{ item }}"
  with_items:
    - "volcano-metrics.tar"
    - "volcano-images.tar"




